export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILED = 'FETCH_FAILED';

export const GET_TOP_LIST_REQUEST = 'GET_TOP_LIST_REQUEST';
export const GET_TOP_LIST_SUCCESS = 'GET_TOP_LIST_SUCCESS';
export const GET_TOP_LIST_FAILED = 'GET_TOP_LIST_FAILED';

