export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILED = 'FETCH_FAILED';

export const GET_TOP_LIST_REQUEST = 'GET_TOP_LIST_REQUEST';
export const GET_TOP_LIST_SUCCESS = 'GET_TOP_LIST_SUCCESS';
export const GET_TOP_LIST_FAILED = 'GET_TOP_LIST_FAILED';

export const GET_LYRIC_REQUEST = 'GET_LYRIC_REQUEST';
export const GET_LYRIC_SUCCESS = 'GET_LYRIC_SUCCESS';
export const GET_LYRIC_FAILED = 'GET_LYRIC_FAILED';

// 请求歌单分类列表
export const GET_CAT_LIST_REQUEST = 'GET_CAT_LIST_REQUEST';
export const GET_CAT_LIST_SUCCESS = 'GET_CAT_LIST_SUCCESS';
export const GET_CAT_LIST_FAILED = 'GET_CAT_LIST_FAILED';

// 请求推荐歌单 actionType
export const GET_RECOMMEND_PLAYLIST_REQUEST = 'GET_RECOMMEND_PLAYLIST_REQUEST';
export const GET_RECOMMEND_PLAYLIST_SUCCESS = 'GET_RECOMMEND_PLAYLIST_SUCCESS';
export const GET_RECOMMEND_PLAYLIST_FAILED = 'GET_RECOMMEND_PLAYLIST_FAILED';

// 核心模块，播放器全局 actionType
export const SET_PLAYING_LIST = 'SET_PLAYING_LIST';
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX';
export const SET_AUDIO_ELEMENT = 'SET_AUDIO_ELEMENT';
export const SET_PLAYING = 'SET_PLAYING';
export const SET_LYRIC = 'SET_LYRIC';
