export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILED = 'FETCH_FAILED';

export const GET_TOP_LIST_REQUEST = 'GET_TOP_LIST_REQUEST';
export const GET_TOP_LIST_SUCCESS = 'GET_TOP_LIST_SUCCESS';
export const GET_TOP_LIST_FAILED = 'GET_TOP_LIST_FAILED';

// 核心模块，播放器全局状态
export const SET_PLAYING_LIST = 'SET_PLAYING_LIST';
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX';
export const SET_AUDIO_ELEMENT = 'SET_AUDIO_ELEMENT';
export const SET_PLAYING = 'SET_PLAYING';
